version: '2'

services:

  back-end:
    build: back-end/
    # volumes: # - D:\web\full-stack\chat-plombier\back-end:/app/back-end
    ports:
      - 3000:3000
    command: node index.js
    env_file:
      - .env