version: '2'

services:
  front-end:
    build: front-end/
    ports:
      - 3001:3001
    command: npm start
    env_file:
      - .env

  back-end:
    build: back-end/
    # volumes: # - D:\web\full-stack\chat-plombier\back-end:/app/back-end
    ports:
      - 3002:3002
    command: node index.js
    env_file:
      - .env
