// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from "contentful";
import { Document } from "@contentful/rich-text-types";

export interface ITestFildFields {
  /** test titile */
  testTitile: string;

  /** description */
  description: string;

  /** rich */
  rich: Document;
}

/** fild for testion
 */

export interface ITestFild extends Entry<ITestFildFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "testFild";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ITestListFields {
  /** title */
  title: string;

  /** id */
  id?: string | undefined;

  /** price */
  price: string;
}

export interface ITestList extends Entry<ITestListFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "testList";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export type CONTENT_TYPE = "testFild" | "testList";

export type IEntry = ITestFild | ITestList;

export type LOCALE_CODE = "en-US";

export type CONTENTFUL_DEFAULT_LOCALE_CODE = "en-US";
